require:
  - rubocop-minitest
  - rubocop-rake

inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

# Match print_width option in .streerc
Layout/LineLength:
  Max: 100
